### ISSUE TITLE
Interference with RubyMotionQuery::App:Class

### ISSUE THREAD

**Issue by andersennl** [clearsightstudio/Parsistence#5]
Hi, I've just encountered an interesting error. I'm working on an `RedPotion` app which uses `RedAlert`, or more precicely RedAlert's `app.make_button` command. Long story short, if I add the `parsistence gem` to my project, the `app.make_button` command fails with this error:

```
2015-05-31 09:10:47.892 myapp 2[62109:19853849] home_table_screen.rb:50:in `gram_button': undefined method `make_button' for #<UIApplication:0x111a207d0> (NoMethodError)
2015-05-31 09:10:47.898 myapp 2[62109:19853849] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'home_table_screen.rb:50:in `gram_button': undefined method `make_button' for #<UIApplication:0x111a207d0> (NoMethodError)
'
*** First throw call stack:
(
  0   CoreFoundation                      0x000000010421bc65 __exceptionPreprocess + 165
  1   libobjc.A.dylib                     0x0000000100e27bb7 objc_exception_throw + 45
  2   myapp 2                           0x0000000100539e0f _ZL10__vm_raisev + 399
  3   myapp 2                           0x0000000100539f3d rb_vm_raise + 205
  4   myapp 2                           0x0000000100436e39 rb_exc_raise + 9
  5   myapp 2                           0x00000001005381b2 rb_vm_method_missing + 786
  6   myapp 2                           0x000000010050b105 rb_vm_dispatch + 5925
  7   myapp 2                           0x000000010050989d rb_vm_trigger_method_missing + 1053
  8   myapp 2                           0x000000010050aaff rb_vm_dispatch + 4383
  9   myapp 2                           0x000000010013ea3c vm_dispatch + 1436
  10  myapp 2                           0x00000001003cc4b3 rb_scope__gram_button__ + 355
  11  myapp 2                           0x00000001003cca3d __unnamed_43 + 13
  12  UIKit                               0x0000000102d4ada2 -[UIApplication sendAction:to:from:forEvent:] + 75
  13  UIKit                               0x0000000102d4ada2 -[UIApplication sendAction:to:from:forEvent:] + 75
  14  UIKit                               0x0000000102e5c54a -[UIControl _sendActionsForEvents:withEvent:] + 467
  15  UIKit                               0x0000000102e5b919 -[UIControl touchesEnded:withEvent:] + 522
  16  UIKit                               0x0000000102d97998 -[UIWindow _sendTouchesForEvent:] + 735
  17  UIKit                               0x0000000102d982c2 -[UIWindow sendEvent:] + 682
  18  UIKit                               0x0000000102d5e581 -[UIApplication sendEvent:] + 246
  19  UIKit                               0x0000000102d6bd1c _UIApplicationHandleEventFromQueueEvent + 18265
  20  UIKit                               0x0000000102d465dc _UIApplicationHandleEventQueue + 2066
  21  CoreFoundation                      0x000000010414f431 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
  22  CoreFoundation                      0x00000001041452fd __CFRunLoopDoSources0 + 269
  23  CoreFoundation                      0x0000000104144934 __CFRunLoopRun + 868
  24  CoreFoundation                      0x0000000104144366 CFRunLoopRunSpecific + 470
  25  GraphicsServices                    0x00000001061d1a3e GSEventRunModal + 161
  26  UIKit                               0x0000000102d49900 UIApplicationMain + 1282
  27  myapp 2                           0x0000000100146e9f main + 111
  28  libdyld.dylib                       0x0000000105d51145 start + 1
  29  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NoMethodError
```

As I had a similar issue before: https://github.com/infinitered/redpotion/issues/97 , I noticed the following line: 
`undefined method 'make_button' for #<UIApplication:0x111a207d0>`, 
which is different to the line in the issue before:
`undefined method 'make_button' for RubyMotionQuery::App:Class (NoMethodError)`.

So adding the `parsistence gem` seems to change `RubyMotionQuery::App:Class` to `#<UIApplication:0x111a207d0>`. 

I don't quite understand why the class gets changed but I can reproduce this error by adding and removing the `parsistence gem` from the gemfile. Is this expected behavior in any way? Thanks a lot!

**Comment by jamonholmgren** [comment]
Hey @andersennl ! Just saw this. Will take a look.

**Comment by andersennl** [comment]
Thanks @jamonholmgren !

**Comment by jamonholmgren** [comment]
Tried to reproduce, but it didn't crash.

https://github.com/jamonholmgren/parsistence-issue-5

Did I miss something?

**Comment by andersennl** [comment]
That's weird, I was sure that I reduced my code to a minimum so that this was the only thing left. I'll try to figure out what else it could be. As it happens as sons as I as the gem I was pretty sure It had to be related. Thanks for taking a look! I'll come back to you as soon as I know more.
